services:
  onyx.products.api:
    image: ${DOCKER_REGISTRY-}onyxproductsapi
    build:
      context: .
      dockerfile: src/Api/Dockerfile

  db:
    image: postgres
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Password1
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
