@api = {{hostname}}

# @name auth

POST {{api}}/auth HTTP/2
Content-Type: application/json
Accept: application/json
{ 
  "username": "{{username}}",
  "password": "{{password}}"
} 

###

GET {{api}}/products/
Accept: application/json
x-api-version:1.0
Authorization: Bearer {{auth.response.body.$.token}}

###

GET {{api}}/products/SHO-CAS-WHI-001
Accept: application/json
x-api-version:1.0
Authorization: Bearer {{auth.response.body.$.token}}

###

GET {{api}}/products?Colour=%23008000
Accept: application/json
x-api-version:1.0
Authorization: Bearer {{auth.response.body.$.token}}

###

GET {{api}}/products?Colour=Brown
Accept: application/json
x-api-version:1.0
Authorization: Bearer {{auth.response.body.$.token}}

###